---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/auth/authentik
      targetRevision: main
      ref: repo
    - repoURL: "https://charts.goauthentik.io"
      chart: authentik
      targetRevision: 2025.8.3
      helm:
        releaseName: authentik
        valueFiles:
          - $repo/kubernetes/apps/auth/authentik/values.sops.yaml
  destination:
    name: in-cluster
    namespace: auth
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
