{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "immich-postgresql-user",
    "namespace": "home-services",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "immich-postgresql-user",
        "namespace": "home-services",
        "creationTimestamp": null
      },
      "type": "generic"
    },
    "encryptedData": {
      "password": "AgAyDI9WuOp/bdqu7wpqyMjFGmd3u2hxNz0YDMxgibj5Migu3pKGLe8QnQgYdf80CXOO8v6XWP+yHBl9FXfEdXx0fhXjty1Qj+yV2txdvJWhOJU8Sc8gr3adkrT+haIsjeaXh3ODwTFAO399tVihRAs8aHbHZWCElgO502fmnEWLlNz3Qsm5F6hjR2Hsisl4hFERCPVr/swzNTl8+Pc73Rxvn84INbyV12Xa9UAm358XW4zAGHARuOKwr6REC1SVFKaT+ZmyyZshABTe/J9SZ1jwD1UclvcvhtASC2q89ri0XAXHw1ZzRKWE42ZuQ4nXObgZq01j/t7n4vmPX8Kv4WknQP9l938N1qsbk1wcwAHW+lc7/ZVTvNLvmgkQGnJsdbAbZjGx+lBLEqnknGIO9k6QPfni5pfH1sP2bcQpXGX9e8aIekRyJtdtpM/ZEGdqzqbMmFlC6yIGDCtarFswDz8leiEKcs0qF8eUAbpEqAuwalv7K8Bn8fs0dACq6G5JmByK55tfsxAt1qN8husO7aYK3g2sOqNC78kNWtoM/EjN4G0Ey30HqvVNDdQjRFSHYTLCahwoga2TJ1zezxNDJ4IDf7G90vz0zql4+hG1JmWqDqKT4R2QR7oUYufh1BF4UlS+SJ3zveVWEIBMNPHKqwenDz6jqjgPo80O1dZNuQADWrUSpcp2GNtUU1N0ElMaSyyYkuEk61E/P6RtQ/3gYehR5NNYLnipbSyKOuSZwthanMlluEn95cNBnMoB/0JbN5LfaWvjghN3fiV1c5GsxJ/S",
      "username": "AgBvX3WNe5Y/NuQdhtytapSLGhaHL9+o5mM0q2luS/ScYXAETFLcZA/V3C7ScGisQKzxZ4tSaEOytH4WduCABgWtopJil3z5nUceLAHoW+ZMrxxOP6/cb/8Nuh91vkO0naZuGH3jqBl69F/43We0Otz5y6dgj42VvhicqjnLoPT4bwDi4Pd5nCqQuiBvS6spKhjKRGUzdWW/UvuexGYhBVDtbO4xOYdLEDV539utZxhazjzdNL0sKuuOXDT3v7rEXUgU68MfvwVlJP3wNNPVaTgXNZJb6oq16L4CJ+uO7Od8QYvvGfdAx+jQU8EpDjxqNqjXF7yHqt6YvL/PK3PspWbY2grMpyjcHD2AlnDLf/Lkx4va2NIjXvgA2LaTXKfnpsksQ1eV9uj44kb+60lD5zwx7JDg/DjaHMofWZBfDMv7BuUrre0kJ3U4/yeEmFpn3sNWEjYzWaGRjriPfUbJfr+LsCjXq4863NwW2oI2NjRzskstonGiRjjgevHj77NiBKNja9LsxBFEPJU0xApVHhMh7o0O0mM2pwogDLLy5c8foV17sGwZkafhfG7KHw7e77EU7Jn6jJctTyTI9DGNhSjq7glLyyxOie3cjg3MWqGrsNq/hy6Vij4FmDqOzg/JIyeqoNHemh1HAzMKBqmJV9ooy2oTJkNDPNWPU8Yq/cGjB2GK9AtdrH51EXA/LMxU9rhNoVZnRN4="
    }
  }
}
