apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
spec:
  imageName: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.3.0
  instances: 1

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgresql-user

  storage:
    size: 10Gi
    storageClass: nas-iscsi
