---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/home-services/navidrome
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: home-services
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
