---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-class
provisioner: kubernetes.io/fake-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  storageClassName: nfs-class
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.16
    path: "/mnt/main-pool/plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: home-services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-class"
  resources:
    requests:
      storage: 4Ti
  volumeName: jellyfin-media
