---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/kube-system/reflector
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/emberstack/helm-charts/reflector
      chart: reflector
      targetRevision: 9.1.33
      helm:
        releaseName: reflector
        valueFiles:
          - $repo/kubernetes/apps/kube-system/reflector/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
