---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/logging/alloy
      targetRevision: main
      ref: repo
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: alloy
      targetRevision: 1.0.3
      helm:
        releaseName: alloy
        valueFiles:
          - $repo/kubernetes/apps/logging/alloy/values.yaml
  destination:
    name: in-cluster
    namespace: logging
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
