---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/logging/grafana
      targetRevision: main
      ref: repo
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: grafana
      targetRevision: 8.15.0
      helm:
        releaseName: grafana
        valueFiles:
          - $repo/kubernetes/apps/logging/grafana/values.sops.yaml
  destination:
    name: in-cluster
    namespace: logging
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
