---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/logging/prometheus
      targetRevision: main
      ref: repo
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: prometheus
      targetRevision: 27.32.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $repo/kubernetes/apps/logging/prometheus/values.yaml
  destination:
    name: in-cluster
    namespace: logging
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
