---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/name: navidrome
  name: navidrome-data
  namespace: home-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-iscsi
  volumeMode: Filesystem
