---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-media
spec:
  storageClassName: nfs-class
  capacity:
    storage: 4Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.0.0.16
    path: "/mnt/main-pool/plex/Music"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-media
  namespace: home-services
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "nfs-class"
  resources:
    requests:
      storage: 4Ti
  volumeName: navidrome-media
