---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/operators/cloudnative-pg
      targetRevision: main
      ref: repo
    - repoURL: "https://cloudnative-pg.github.io/charts"
      chart: cloudnative-pg
      targetRevision: 1.26.0
      helm:
        releaseName: cloudnative-pg
        valueFiles:
          - $repo/kubernetes/apps/operators/cloudnative-pg/values.yaml
  destination:
    name: in-cluster
    namespace: argo-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
