controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 34
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mjwood.org
    hosts:
      - host: '{{ .Release.Name }}.mjwood.org'
        paths:
          - path: /
            service:
              identifier: app
              port: http
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V0hrUUtxaUJtQWhBQmFh
        TUpKNjhSaXFsSWt2S25RWkRXbzBhM08yamtnCmxqa1RuRUdPQTV3S1NSV2phdkhZ
        dG8yVlM2eTNhdjEvY0xURWJzUUowRlUKLS0tIFdwQi9NVUphM2NQRmF5cjBOM1Fr
        QmhhREZzdC9hUlZYRWM2cDB4cVdKLzAKjptrKQKP41lds/LNQh8zD8BbsU9dH6NN
        EIZzSCpnXc6XacyiJRwJo0t3oOiInw0//CsebitsuoPe/CCsSa5UcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-28T17:19:07Z"
  mac: ENC[AES256_GCM,data:TBcmjiuCkq1//X+ET2I+iLNrfvILQO3PCbac0wz5KOZtt9MYW05p210euGpfg2OLUyvCUFHi19ASCxFkJINksrnTjJeZ4XqXv8D5eBuR73ntzWtPLWoVA4uSKoiYo8qZvyJgi1GIartcAT0zkmL4ocwtaxXRmUWfVu7tPtKE9DM=,iv:rjokmRD8gf3ZF/Xwgd0AkYZFk2ADi7LRtb2oJXRIV4o=,tag:FCETYHIEj8QNA/PgiRs8kQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
