---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-runner
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/forgejo-system/forgejo-runner
      targetRevision: main
      ref: repo
    - repoURL: codeberg.org/wrenix/helm-charts/forgejo-runner
      chart: forgejo-runner
      targetRevision: 0.6.6
      helm:
        releaseName: forgejo-runner
        valueFiles:
          - $repo/kubernetes/apps/forgejo-system/forgejo-runner/values.sops.yaml
  destination:
    name: in-cluster
    namespace: forgejo-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
