apiVersion: v1
kind: Service
metadata:
  annotations:
    lbipam.cilium.io/ips: 10.0.0.88
  name: forgejo-ssh
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ssh
      port: 2222
      protocol: TCP
      targetPort: ssh
  selector:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
  sessionAffinity: None
  type: LoadBalancer
