driver:
  config:
    driver: freenas-api-iscsi
    httpConnection:
      protocol: https
      apiKey: ENC[AES256_GCM,data:7B4tklC/jNFZIhRqyA5xbyKtFJ+Ac/u0gN5saF0jty9acXymgimCeCNefmeFMWRUJES+fi793aJdG4uGTvvf5cYo,iv:+qXnlX/SBLB4eetnH7Y2RJZXIjTRuENd+/KHyf/DPFY=,tag:iwO+OjqKXKVMF0Q+HgQfNg==,type:str]
      host: 10.0.0.9
      port: 443
      allowInsecure: true
    zfs:
      datasetParentName: nvme/talos/iscsi/volumes
      detachedSnapshotsDatasetParentName: nvme/talos/iscsi/snapshots
      zvolCompression: null
      zvolDedup: null
      zvolEnableReservation: false
      zvolBlockSize: null
    iscsi:
      targetPortal: 10.0.0.9:3260
      targetPortals: []
      interface: null
      namePrefix: csi-
      nameSuffix: -talos
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup: null
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: SSD
      extentAvailThreshold: 0
csiDriver:
  # should be globally unique for a given cluster
  name: org.democratic-csi.freenas-api-iscsi
storageClasses:
  - name: truenas-iscsi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret: null
      controller-publish-secret: null
      node-stage-secret: null
      node-publish-secret: null
      controller-expand-secret: null
volumeSnapshotClasses:
  - name: truenas-iscsi
    parameters:
      detachedSnapshots: "true"
node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcmpUZ3VRSnNTWlhkQURr
        M25wT2Y1YThQdW0rb084aGlVZjFGUW45RUFZCi9FbS9GS3ZpQnk2SVhENHVSeGdW
        VHpNRUQ0MnZucWptUEhQazMzcEtqWk0KLS0tIEdXanpwZ3lEd3g1SzMyZEgyZ2E5
        R0wrZG1zdEZjb0lTQnVHWmIvbHl4bVkKLOrSIOBL3cqjsWPmWp050eiKE3bFf0UI
        7zuAqnm4BX9LXgzodSLVyIbR8K1Bs6tCvDsIMW/vVC8D3bGFd+wZsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T15:17:57Z"
  mac: ENC[AES256_GCM,data:xjjRP5eSAiVg9j/mArJjXSd67jk5l9IJBfHDvo0IkGubOSqJWPW+SjkHeSdmWrjROnGm4gRKTbLURedWSbd4eHdPTi/3GDlUowO6Taxn8TUangyWTkbULxFM30FsV3PZZGXUp2tuUJ/Gg9S28jSBAAe29N7JaBwS3NVadHwfmBo=,iv:cuZ8YII6ai/diKrcvZrVyp9tR9oN2xlhF05c52+DH0k=,tag:mk95WaYadBrOyxoEhlTtmw==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key)$
  mac_only_encrypted: true
  version: 3.10.2
