driver:
  config:
    driver: freenas-api-iscsi
    httpConnection:
      protocol: https
      apiKey: ENC[AES256_GCM,data:AX5Wv79UV/EK7aMLsXMfCm9fcwP06O3A4CyQBsxbd7mf+rmAUu++ftutv7A0/68t+fQ/AneNlakJXuZbbEr4RG+x,iv:67SnQrzdmcBAXMkmC2IOR15VhGBgVaCOA1FeMnv6U70=,tag:PyHnPg+XHbKR7YWaaMuZZA==,type:str]
      host: 10.0.0.16
      port: 443
      allowInsecure: true
    zfs:
      datasetParentName: main-pool/talos/iscsi/vol
      detachedSnapshotsDatasetParentName: main-pool/talos/iscsi/snap
      zvolCompression: null
      zvolDedup: null
      zvolEnableReservation: false
      zvolBlockSize: null
    iscsi:
      targetPortal: 10.0.0.16:3260
      targetPortals: []
      interface: null
      namePrefix: csi-
      nameSuffix: -talos
      targetGroups:
        - targetGroupPortalGroup: 2
          targetGroupInitiatorGroup: 2
          targetGroupAuthType: None
          targetGroupAuthGroup: null
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: SSD
      extentAvailThreshold: 0
csiDriver:
  # should be globally unique for a given cluster
  name: org.democratic-csi.freenas-api-iscsi
storageClasses:
  - name: truenas-iscsi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret: null
      controller-publish-secret: null
      node-stage-secret: null
      node-publish-secret: null
      controller-expand-secret: null
volumeSnapshotClasses:
  - name: truenas-iscsi
    parameters:
      detachedSnapshots: "true"
node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSlFiT1YrR0RaME85aUY3
        andpcTlDNXFwcGFSVG5SbmNGb1kvUWt1Y0NJCmxpUHlwTFhBQTJEbEhONVZ3U1Mr
        TGx0M3VLNmUrVk15TG5oVXVZWVFrb0UKLS0tIG5YbzhyQUxVWCtwZy8xSnZDUHpz
        am15OC9oSllEdHV3Q0tIR1VHY240MHcKZP/3UBMl/EhS+Y8GVIOcaLcMNGTF18wc
        IOSss0jxnuihhzYavxEIULbiS1WbY1kLkBH88ZGwQzzWIwT4BuCsww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-26T20:12:43Z"
  mac: ENC[AES256_GCM,data:rIAnXpFh9Ve4Gxui00haCw3mWacX2TwYDD6CUf9J9HM5J6lmuXaqxJLKfFvv8lFn2tyTqmu9V1SZSdzm2mtev8gr3B0Y8hWCfXHKaujbHcEHMB0rLwOe3JuW0X1P0iMVsnHD4XD1lVqaRPR2UhD+L8j7BnCXL/TOFTvv1DkTTik=,iv:8/WYgQg2a0C4ird4QBn8QpuXZ3qEGO3u5AWaXgYPnJs=,tag:nAxwZfiCU6UeDylt9xcGhQ==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key)$
  mac_only_encrypted: true
  version: 3.10.2
