agent:
  enabled: true
  persistence:
    size: 20Gi
    storageClass: truenas-flash-nfs
  env:
    WOODPECKER_LOG_LEVEL: debug
server:
  # -- Enable the server component
  enabled: true
  # -- Add environment variables for the server component
  env:
    WOODPECKER_ADMIN: woodpecker,admin,mike
    WOODPECKER_HOST: https://woodpecker.mjwood.org
    WOODPECKER_FORGEJO: "true"
    WOODPECKER_FORGEJO_URL: https://forge.mjwood.org
    WOODPECKER_FORGEJO_CLIENT: dd8bc1b3-ea3b-409f-988c-5f7eac1bd078
    WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:ru25VD07JZ6gVe4oAy9PSsQZsZHS59WXzZzZyn3lrYQXdsGpLTwSeRnIpmtdmdWpe/zz8xLiUrs=,iv:eAWm4kh0C9q20Y8Axo4KwPz8L2cYEhRKvOnkV01rLis=,tag:PEygom2dWefNkom3l33HLg==,type:str]
    WOODPECKER_PLUGINS_PRIVILEGED: docker.io/woodpeckerci/plugin-docker-buildx:latest
    WOODPECKER_LOG_LEVEL: debug
  persistentVolume:
    storageClass: truenas-iscsi
  service:
    port: 80
  ingress:
    enabled: true
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mjwood.org
    ingressClassName: external
    hosts:
      - host: woodpecker.mjwood.org
        paths:
          - path: /
            backend:
              serviceName: woodpecker-server
              servicePort: 80
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNmpRRFpjS0k2MDZVZXd2
        WlUydS9mNUlRM2VFOWhYM1pFUXBZaHRaNkRnCm5OL1hMYkt4RVR1bmlxdFBLeVpa
        M0NndjBLWmRsK0FQSVZxa1NsNW9yeWsKLS0tIFI1WWtGTDhFdTNBZWpWc0h6WlQ5
        L0FhZmNacjdsQ1YvQTVJZUZhL1FDcVkKqM6QmR16kuP5AoNZqcJHwuxRjpnl3xJj
        HI82B6Ygp/wVlnSdnlPhahDRRmLN7RVO9HC57FtgW3KFDoypnREDfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-29T20:02:14Z"
  mac: ENC[AES256_GCM,data:iOxiPqzIo4AVCpP2seQF5HcBpiZAx6aQdP/TMFYBfyTmuAUbPDMug71bXOHCOUza/T9x9QhKw4ZSjjG2LrANIEpD7KGgXMxM7VdUnMk6n15Ha/u+CMdWZmToiX1UKI5X6JZmqIn+UuSXwbwH1X0gakEKopULmziWmWx5nH80ktM=,iv:gIpFoEYdMwRR8BvMZCy+CY2eahF0BoY56a3eMhjXYaQ=,tag:SJ+GXhfrFcMZpTXNe4hOmg==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key|secret|WOODPECKER_FORGEJO_SECRET|token)$
  mac_only_encrypted: true
  version: 3.10.2
