agent:
  persistence:
    size: 20Gi
    storageClass: truenas-flash-nfs
server:
  # -- Enable the server component
  enabled: true
  # -- Add environment variables for the server component
  env:
    WOODPECKER_ADMIN: woodpecker,admin,mike
    WOODPECKER_HOST: https://woodpecker.mjwood.org
    WOODPECKER_FORGEJO: "true"
    WOODPECKER_FORGEJO_URL: https://forge.mjwood.org
    WOODPECKER_FORGEJO_CLIENT: dd8bc1b3-ea3b-409f-988c-5f7eac1bd078
    WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:I3+fTOQzJc9up8femVNWGpJT8Jrkkci8ri+iCVnrNpu1tcDj7tvZIPSDx4qJJbOMGNqZv/4H6Qc=,iv:mbd4DwsJd0Ry2mpHWM+Ckuz+M25EfYjYSk9CcUcdySQ=,tag:5MHQxg3B52Re5qlCb6zrOA==,type:str]
  persistentVolume:
    storageClass: truenas-iscsi
  service:
    port: 80
  ingress:
    enabled: true
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mjwood.org
    ingressClassName: external
    hosts:
      - host: woodpecker.mjwood.org
        paths:
          - path: /
            backend:
              serviceName: woodpecker-server
              servicePort: 80
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOHRkUW5NUHUyQ1ZaaURs
        YXRWS1lJT1hOSGN6eVJzWnV6SVZ0NTZkVUJzCk9HTGF5VHBMckNRdVpubS9TNnpM
        ZWk0TnNDNm1Kdnp5TjhuN05NRGxnKzQKLS0tIE5JdlYyaStlM210NGJ2YzlZMmw4
        cHVQMFZRMDVzZnovbE5JcjhYbll0encKSG9mQxqGHGhPwXx7OZWi+EQmTA0MPJ50
        oGYOlEdB1k7/+/rNMvQdPhL61PyVgMncyXyDlEBn+np5u7zKquct7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-01T15:52:33Z"
  mac: ENC[AES256_GCM,data:OH5PQQHP8wjkX8E/8uPzocIxBS+jwW4gudPbPSAKL24yJcsnTqbqRp0TeiwwFLf183xu9huHkmSWqc0Ayc956uNVCBXwG+0edOuqNnZVAwlIX1J6zOXPzIMTYiNdzw1GccygwWjuiqbSP+cSzG8amgT08w3wjmzQsXsUvxvjm/c=,iv:tKPUCA8mHQmyvt5FTsEQhwj8hnVx6kBbPmRKITL5fKo=,tag:he7t8IsmydSxO1VZpf0xjQ==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key|secret|WOODPECKER_FORGEJO_SECRET)$
  mac_only_encrypted: true
  version: 3.10.2
