agent:
  enabled: true
  persistence:
    size: 20Gi
    storageClass: truenas-flash-nfs
server:
  # -- Enable the server component
  enabled: true
  # -- Add environment variables for the server component
  env:
    WOODPECKER_ADMIN: woodpecker,admin,mike
    WOODPECKER_HOST: https://woodpecker.mjwood.org
    WOODPECKER_FORGEJO: "true"
    WOODPECKER_FORGEJO_URL: https://forge.mjwood.org
    WOODPECKER_FORGEJO_CLIENT: dd8bc1b3-ea3b-409f-988c-5f7eac1bd078
    WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:x8ebo7SBbhC9HnibJ6+xIWirvXZZgCSYCk8MqsZr1DOw7xag0UmWrBTcPljhWl8hJDyRCrI0CrY=,iv:kx1cQWEivsDX36e0Fgz81YRtlXIqKrEWuVwu5PTeW50=,tag:xA4v9p7POrnqbH0igI02QA==,type:str]
    WOODPECKER_PLUGINS_PRIVILEGED: plugins/docker
  persistentVolume:
    storageClass: truenas-iscsi
  service:
    port: 80
  ingress:
    enabled: true
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mjwood.org
    ingressClassName: external
    hosts:
      - host: woodpecker.mjwood.org
        paths:
          - path: /
            backend:
              serviceName: woodpecker-server
              servicePort: 80
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTGlkV2VWVFVhQ2NiYjhR
        Ykk3aGxHUjJMMnFUallXSnpvcUpyVXFBRHdjCk9WMldqamZ6Q3VLUldRNjFWaUdJ
        M3d4U0I5YklMMldUWlpHeDBmUDVsMXcKLS0tIHhNbnN6eHRMeXUxL3dmZFRYd1VS
        cU52QXU5TmJhUFUrL1hoN2pqZnBMcFkK1OmjT0Tb3SV5RiPKVesw5wOa8EHFtbS5
        7xkakmLnR9S660QhxXcb8SxhSxyCvlwdDj6GoaitcOwdPdP0TcaRuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-26T19:55:09Z"
  mac: ENC[AES256_GCM,data:aDsktwZiLu2uY/8lIieDPfleMxCwVh2kpVz4CiUaIM9aO0xoQB7G6G04owTmrLZ3cQ8yO5Hto2JX+5cRSR3cwBDVNyjJRsKbmhhEIS/IQaQuIztMDBlSPufFvJ6+Sb4rdJkIurYibTlvhDdu+wZw5SQvrD29hwXiVugSBgvhzDg=,iv:NudGJHx71AT7f9ftXc0BGi/aWh9gT/MpCy6SVRHuLMM=,tag:w8OSRy61lrE+1t08Un8BtA==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key|secret|WOODPECKER_FORGEJO_SECRET|token)$
  mac_only_encrypted: true
  version: 3.10.2
