agent:
  enabled: true
  persistence:
    size: 20Gi
    storageClass: truenas-flash-nfs
server:
  # -- Enable the server component
  enabled: true
  # -- Add environment variables for the server component
  env:
    WOODPECKER_ADMIN: woodpecker,admin,mike
    WOODPECKER_HOST: https://woodpecker.mjwood.org
    WOODPECKER_FORGEJO: "true"
    WOODPECKER_FORGEJO_URL: https://forge.mjwood.org
    WOODPECKER_FORGEJO_CLIENT: dd8bc1b3-ea3b-409f-988c-5f7eac1bd078
    WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:IeHGspoLfEfo6zIPM2PIXbpot8++TwupZdwSgz3V8Tzu4kP8IBqrjMQsJ7CK8/wJQno6yCKP0oE=,iv:6eS5J3YAGNGnZAYybYwC0qU2ZP115asT3DB0pqcAUfM=,tag:mlDDfnV6iKbEfg0ZG88LLQ==,type:str]
    WOODPECKER_PLUGINS_PRIVILEGED: docker.io/woodpeckerci/plugin-docker-buildx:latest
  persistentVolume:
    storageClass: truenas-iscsi
  service:
    port: 80
  ingress:
    enabled: true
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.mjwood.org
    ingressClassName: external
    hosts:
      - host: woodpecker.mjwood.org
        paths:
          - path: /
            backend:
              serviceName: woodpecker-server
              servicePort: 80
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dWtuYnVVRk8zeklDWDZY
        Y2RiZFNrYjJIcTRHZVZjYk8yL2tPd2RaY0hBCm9YbEI3cUVpSTRWUi85ZFBZcDVX
        NDVNSXVtZXVFeld5V0g0YnpEcWpqdDQKLS0tIGNUNFNsMzBjTm1UMkhxaG1pQXlJ
        TE5PMlE3cmg4NGpHUHpuVjhucDROSmcK8C3cxCI4PcHxlGy19CDpwqssZKjHwCnh
        gbKkuB1smkeDuGEOJ7SwyFir8cbISmnoWQKbQO7i1ZKYI223kp/sZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-28T23:33:23Z"
  mac: ENC[AES256_GCM,data:/5b2o6Tt8Xu7i2+Zg+/5dkHH2iLpFkAqH8mtXgNvZYbif04Ez+j1BnGQWsaSH7oXthlD/TWKEcIA4aQWAHtkIsQHAegXLEsMR5IHjRVwHWM2JhG6gwluR9ltnyfxjjfGpol+r+gNwopGEzVBKtCru7ocrDmuve4cVq7NM2SG9X4=,iv:XkFCaQeuwX2L2ufCInhzQN14Ike/S6DrC5p1Q3Kc6Tw=,tag:uAgDJnkfqTQW2vncEV5pXw==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key|secret|WOODPECKER_FORGEJO_SECRET|token)$
  mac_only_encrypted: true
  version: 3.10.2
