# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:/gRh9AkGuoiiS2TfIRGRw24UvqLaWJOZ1ILVJDN6ZJ4C1h/iFBxYUA==,iv:Gr3h9Aqcddtr3xcgZzpcnsGAhwwPGfZC29tH2Sith0Q=,tag:KdkkVHwnx6txJ2B5YYRwlw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMFAxb0paV2RCcThNSTNO
        a2ZOeXpDYTlkamR1dFB4QUgvVW1iaG1rdlVZCmFiRmZaQXlJbzIwcDZtT1luSGtX
        aG10ZmFOb0hHV2thTE1HM3lJUElNMjQKLS0tIFBacll6RE03eUl6czAwZXFlWkFP
        SXo4aDFIQkwvdkxPU0NjZFQ5VW9mV0kK1pEd96R87L8mUEQVu0xl/Yc8ddg4Oy7k
        XLoHg/AugJMJJVvrAkCSA9uoteZfDD3nzftpkmvRudeglEah8elxUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-28T17:19:07Z"
  mac: ENC[AES256_GCM,data:dB5BXny7W4+X29aZaxVrsNAoalb2UH+h0o4EOwkjGaWoi2yHy6tbpViwuu4oEOs+3tPBRabZCM2PXGlUa6DmqREaeDMMBHmP2iJSTLInyX96VxhtuzfILyOo7Dx3Cje/uegfqKgMg261P0ZEQR9wL3rQVGGbBYGm5PPtup2BofU=,iv:TG0xdcOoUaYxwNTe+sKJdoM+GJ4axItkHPN6T0e/IY4=,tag:UAUVGAe2QEIG6X2vGOtV5Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
