---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-bedrock
  namespace: home-services
  labels:
    app: mc-bedrock
spec:
  selector:
    matchLabels:
      app: mc-bedrock
  serviceName: "mc-bedrock"
  replicas: 1
  template:
    metadata:
      name: mc-bedrock
      labels:
        app: mc-bedrock
    spec:
      containers:
        - name: mc-bedrock
          image: docker.io/itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 2Gi
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: survival
            - name: DIFFICULTY
              value: normal
            - name: SERVER_NAME
              value: "Container Blocks"
            - name: LEVEL_NAME
              value: "woodsville"
            - name: WHITE_LIST
              value: "false"
            - name: ONLINE_MODE
              value: "true"
            - name: ALLOW_CHEATS
              value: "false"
            - name: TICK_DISTANCE
              value: "8"
          volumeMounts:
            - mountPath: "/data"
              name: mc-bedrock
  volumeClaimTemplates:
    - metadata:
        name: mc-bedrock
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "truenas-flash-iscsi"
        resources:
          requests:
            storage: 5Gi
