---
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock
  namespace: home-services
  labels:
    app: mc-bedrock
  annotations:
    lbipam.cilium.io/ips: 10.0.0.31
spec:
  selector:
    app: mc-bedrock
  ports:
    - port: 19132
      targetPort: 19132
      protocol: UDP
  type: LoadBalancer
