# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.0.90:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.0.90"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

allowSchedulingOnControlPlanes: false

nodes:
  - hostname: "talos-ctl-1"
    ipAddress: "10.0.0.91"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:8d:d6:cc"
        dhcp: false
        addresses:
          - "10.0.0.91/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.0.90"
  - hostname: "talos-ctl-2"
    ipAddress: "10.0.0.92"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:97:22:26"
        dhcp: false
        addresses:
          - "10.0.0.92/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.0.90"
  - hostname: "talos-ctl-3"
    ipAddress: "10.0.0.93"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:91:ee:41"
        dhcp: false
        addresses:
          - "10.0.0.93/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.0.90"
  - hostname: "talos-worker-1"
    ipAddress: "10.0.0.94"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:81:85:0a"
        dhcp: false
        addresses:
          - "10.0.0.94/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
  - hostname: "talos-worker-2"
    ipAddress: "10.0.0.95"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:f5:ca:60"
        dhcp: false
        addresses:
          - "10.0.0.95/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
  - hostname: "talos-worker-3"
    ipAddress: "10.0.0.96"
    installDisk: "/dev/vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/c9078f9419961640c712a8bf2bb9174933dfcf1da383fd8ea2b7dc21493f8bac
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:80:6c:fe"
        dhcp: false
        addresses:
          - "10.0.0.96/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

# Worker node patches
worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
