---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker
  namespace: argo-system
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/michaeljwood/home-lab.git"
      path: kubernetes/apps/woodpecker/woodpecker
      targetRevision: main
      ref: repo
    - repoURL: oci://ghcr.io/woodpecker-ci/helm
      chart: woodpecker
      targetRevision: 3.3.0
      helm:
        releaseName: woodpecker
        valueFiles:
          - $repo/kubernetes/apps/woodpecker/woodpecker/values.sops.yaml
  destination:
    name: in-cluster
    namespace: woodpecker
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
