replicaCount: 1
image:
  registry: harbor.mjwood.org
  repository: forgejo/forgejo/runner
  pullPolicy: Always
runner:
  config:
    # -- create a secret by run: forgejo-runner register --no-interactive --token {TOKEN} --name runner --instance https://next.forgejo.org
    create: true
    instance: https://forge.mjwood.org
    name: kube-runner
    token: ENC[AES256_GCM,data:gKLAhqAktPkkWa+57XJgmhRBmJI3EoxtTeLVaL+PkJnGey4meAYbkw==,iv:eBlQ6VSUo+4tvkNQuKr2Hj1VEx1SzD9W2j4+pxAh7T4=,tag:Fcou2dhrpzd4+ejb5fauig==,type:str]
    # based on https://code.forgejo.org/forgejo/runner/commit/1139bb7d12ff7889694b24731707e153678ab960
    file:
      log:
        # -- The level of logging, can be trace, debug, info, warn, error, fatal
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        level: info
        # -- The level of logging for jobs, can be trace, debug, info, earn, error, fatal
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        job_level: info
      runner:
        # -- Extra environment variables to run jobs.
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        envs:
          DOCKER_HOST: tcp://localhost:2376
          DOCKER_TLS_VERIFY: "0"
        fetch_timeout: 5s
        fetch_interval: 2s
        # -- The labels of a runner are used to determine which jobs the runner can run, and how to run them.
        # Like: ["macos-arm64:host", "ubuntu-latest:docker://node:16-bullseye", "ubuntu-22.04:docker://node:16-bullseye"]
        # If it's empty when registering, it will ask for inputting labels.
        # If it's empty when execute `deamon`, will use labels in `.runner` file.
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        labels:
          - kube
      cache:
        # -- Enable cache server to use actions/cache.
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        enabled: false
        # -- The directory to store the cache data.
        # If it's empty, the cache data will be stored in $HOME/.cache/actcache.
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        dir: ""
        # -- The host of the cache server.
        # It's not for the address to listen, but the address to connect from job containers.
        # So 0.0.0.0 is a bad choice, leave it empty to detect automatically.
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        host: ""
        # -- The port of the cache server.
        # 0 means to use a random available port.
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        port: 0
        # -- The external cache server URL. Valid only when enable is true.
        # If it's specified, act_runner will use this URL as the ACTIONS_CACHE_URL rather than start a server by itself.
        # The URL should generally end with "/".
        # @section -- Configuration yaml of runner (see: https://code.forgejo.org/forgejo/runner/src/branch/main/internal/pkg/config/config.example.yaml)
        external_server: ""
dind:
  image:
    registry: harbor.mjwood.org
    repository: hub/library/docker
    pullPolicy: Always
    tag: 28.3.3-dind
  # -- We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # @section -- Docker in Docker
  resources: {}
kubectl:
  image:
    registry: harbor.mjwood.org
    repository: hub/bitnami/kubectl
    pullPolicy: Always
    tag: 1.33.4
sops:
  age:
    - recipient: age1m0lm4afkysxufghhpez3p0wjzchms5gpadc085p3ukqh75hyvanst3lrvr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNUNkQ1BVVTM5a2xEN2VT
        a0d2OTVQbUJ3U21tS2lEWjA4SGpNekFCbEVjCkZqRzVkdUtmSFl4MnR6MWxjcytq
        dGhHOXU0dm8xNHhseFlkTTQ1aHR2UUEKLS0tIHErSDFqaGVjZkVXZWVONGNkUmU5
        YU1nK0NKUWpxR3JyS0ZjZ0xNNTJZbEUK8uwP1XmxuiSS4hb0ToMGWxARIN5pHdXy
        WlHWGBXEQcGmb9bJxNPqVfm4SET4SyyD5UmSn5fX/h7WeznpS/rzkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T23:29:06Z"
  mac: ENC[AES256_GCM,data:GgRk/usCsXoVHmtnffoM+vitE8ElK2DJBjWGd7vYh9osARBlGnDu/vJMOAkasI1CBpCWPuPCkl9834A3468n3HFCXomYysZ6MUoBhV5rSh56w16WiGsWQaJBDToON+/xuJwDx2HnD5Nh5Sbw1yQ22uFlVg1ngfLQ48Bfgxl92BU=,iv:1nwQjWwZPFMYtcPy1f70M3/6eOrILCNBRJFEkGsQKhc=,tag:TsWnn8isM3q7x8x5w6JQKA==,type:str]
  encrypted_regex: ^(data|stringData|apiKey|rootPassword|secretKey|adminPassword|basicAuthPassword|password|secret_key|secret|WOODPECKER_FORGEJO_SECRET|token)$
  mac_only_encrypted: true
  version: 3.10.2
